name: Build Dart Examples and Publish to GitHub Pages

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v4

    - name: Set up Dart
      uses: dart-lang/setup-dart@v1
      with:
        channel: stable

    - name: Install dependencies
      run: dart pub get

    - name: Build examples
      run: |
        for dir in examples/*; do
          if [ -d "$dir" ]; then
            example=$(basename "$dir")
            dart compile js --no-source-maps -m "./examples/$example/$example.dart" -o "./examples/$example/$example.js" -O4
          fi
        done

    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './examples'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
