name: Build Dart Examples and Publish to GitHub Pages

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Dart
      uses: dart-lang/setup-dart@v1
      with:
        channel: stable

    - name: Install dependencies
      run: dart pub get

    - name: Build examples
      run: |
        for dir in examples/*; do
          if [ -d "$dir" ]; then
            example=$(basename "$dir")
            dart compile js --no-source-maps -m "./examples/$example/$example.dart" -o "./examples/$example/$example.js" -O4
          fi
        done

    - name: Set up Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Deploy to GitHub Pages
      run: |
        mkdir -p gh-pages

        cp -r examples/* gh-pages/

        cd gh-pages

        git init
        git add .
        git commit -m "Deploy compiled examples"
        git branch -M master
        git remote add origin https://github.com/${{ github.repository }}.git
        git push -f origin master:gh-pages

    - name: Clean up
      run: |
        rm -rf gh-pages
